# remap prefix to ALT + a
set -g prefix M-a
unbind C-b
bind C-a send-prefix

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Turn auto-renaming of windows off
set-option -g allow-rename off

#Index numbering should start at 1
set -g base-index 1
# Base Index should start from 1 instead of 0
set-window-option -g pane-base-index 1
setw -g pane-base-index 1
set -g pane-base-index 1
set-option -g pane-base-index 1


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# split panes using | and -
bind o split-window -h
bind p split-window -v
unbind '"'
unbind %

set -g status-keys vi
set -g history-limit 10000





# DESIGN TWEAKS
# clock mode
# setw -g clock-mode-colour yellow
#
# # copy mode
# setw -g mode-style 'fg=black bg=red bold'
#
# # panes
# set -g pane-border-style 'fg=red'
# set -g pane-active-border-style 'fg=yellow'
#
# # statusbar
# set -g status-position bottom
# set -g status-justify left
# set -g status-style 'fg=red'
#
# set -g status-left ''
# set -g status-left-length 10
#
# set -g status-right-style 'fg=black bg=yellow'
# set -g status-right '%Y-%m-%d %H:%M '
# set -g status-right-length 50
#
# setw -g window-status-current-style 'fg=black bg=red'
# setw -g window-status-current-format ' #I #W #F '
#
# setw -g window-status-style 'fg=red bg=black'
# setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
#
# setw -g window-status-bell-style 'fg=yellow bg=red bold'
#
# # messages
# set -g message-style 'fg=yellow bg=red bold'
#


# Set status line, windows, pane and message colors.
set -g message-style "bg=#1c1c1c,fg=#9c9c9c"
set -g pane-active-border-style "bg=#080808,fg=#80a0ff"
set -g pane-border-style "bg=#080808,fg=#303030"
set -g status-style "bg=#1c1c1c,fg=#9c9c9c"
setw -g window-status-activity-style none
setw -g window-status-current-style "bg=#353946,fg=#80a0ff"
# Set active and inactive window style.
setw -g window-status-current-format " #I #[fg=#9c9c9c] #[fg=default]#W #[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "
setw -g window-status-format " #I  #W #[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "

# Set status bar components and style.
set -g status-left "#[fg=#f09479]⠶ #[fg=#80a0ff]#S@#h "
if-shell '[[ $(uname) = Darwin ]]' \
    'set -g status-right "%a %d %b  #[fg=#80a0ff]%I:%M%p"' \
    'set -g status-right "%a %d %b  #[fg=#80a0ff]%I:%M%P"'
